image: Visual Studio 2017

environment:
  matrix:
  - host: x86_64-pc-windows-msvc
    targets: aarch64-pc-windows-msvc
    channel: nightly
  - host: i686-pc-windows-msvc
    channel: nightly
  - host: x86_64-pc-windows-gnu
    channel: nightly
  - host: i686-pc-windows-gnu
    channel: nightly
  - host: x86_64-pc-windows-gnu
    channel: 1.6.0
matrix:
  allow_failures:
    - target: aarch64-pc-windows-msvc

install:
  - ps: >-
      if (ls -r . -fi "*.rs" | sls "`t") { throw "Found tab character" }
      appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe;
      .\rustup-init.exe -y --default-toolchain $env:channel --default-host $env:host;
      $env:PATH = "$env:PATH;${env:USERPROFILE}\.cargo\bin";
      if ($env:targets) { $env:targets -split " " | %{
        rustup target add $_;
      }}
      rustc -vV;
      cargo -vV;

build_script:
  - ps: >-
      cargo build;
      cargo build --release;
      cargo build --features "everything debug impl-default";
      cargo test --features "everything debug impl-default";
      if ($env:targets) { $env:targets -split " " | %{
        cargo build --target=$_;
        cargo build --target=$_ --release;
        cargo build --target=$_ --features "everything debug impl-default";
        cargo test --target=$_ --features "everything debug impl-default" --no-run;
      }}

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/d3d6703d143c888f0a8a
