[package]
name = "winapi"
version = "0.1.4"
authors = ["Peter Atashian <retep998@gmail.com>"]
description = "Types and constants for WinAPI bindings. See README for list of crates providing function bindings."
documentation = "https://retep998.github.io/doc/winapi/"
repository = "https://github.com/retep998/winapi-rs"
readme = "README.md"
keywords = ["Windows", "FFI", "WinSDK"]
license = "MIT"
